### ISSUE TITLE
Question about the data preparation

### ISSUE THREAD

**Issue by wudongming97** [YujiaoShi/cross_view_localization_SAFA#5]
Hi,
When I run data_preparation.py for polar transform, I found the generated data by me cannot make the training convergence. Besides, the link about the prepared polar data of you is unavailable.

**Comment by shiyujiao** [comment]
> Hi,
> When I run data_preparation.py for polar transform, I found the generated data by me cannot make the training convergence. Besides, the link about the prepared polar data of you is unavailable.

Hi, can you please send me severe examples of your generated polar transform images, and their corresponding original satellite images and ground-level panoramas? My email address is yujiao.shi@anu.edu.au.

**Comment by YujiaoShi** [comment]
> Hi,
> When I run data_preparation.py for polar transform, I found the generated data by me cannot make the training convergence. Besides, the link about the prepared polar data of you is unavailable.

Hi, can you please send me several examples of your generated polar transform images, and their corresponding original satellite images and ground-level panoramas? My email address is yujiao.shi@anu.edu.au.
