### ISSUE TITLE
Activation function of Spatial-aware Importance Generator

### ISSUE THREAD

**Issue by TedLentsch** [YujiaoShi/cross_view_localization_SAFA#8]
I have studied the [code](https://github.com/shiyujiao/cross_view_localization_SAFA/blob/6838ec09fe3b166fd33201d4538124082f792921/script/spatial_net.py#L5) of the SPE module. I cannot find an activation function in the code, whereas I expected it to be applied to the output of the first linear layer of the Spatial-aware Importance Generator. Is it true that no activation function is used? If so, is there a reason for this?

**Comment by YujiaoShi** [comment]
Hi, thanks for pointing out this problem. It seems that the activation function is accidently missed when writing the code. Not sure how the performance will change when adding it back.

**Comment by TedLentsch** [comment]
Thanks for your quick reply. I propose to use a ReLU after the first layer and you could also add an activation function after the second layer like a sigmoid, but that is optional I think. I expect the performance to change because the network can represent functions with a higher complexity when the ReLU is added. Two subsequent linear layers without activation are equal to a single linear layer (with a couple of constraints) and these two subsequent linear layers are limited to linear relations.
